# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6426cfdda63fbbc09a04b827c6389a612c69c6ecd991a8059148d3ffb8ca71eed3c35531ed097c31e1c9fe5d4ee7489ed4ebd19552b7e44b3739d54da12c328

test:
  secret_key_base: 081cdce28c98e40ede611d7b805be2721d8c0463e5f568833abc144496d6a68925927af9f8d9461bcc5a2a384fb2754fa9fa970da6af3c0f1f7db42708304206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
